[DMN Designer] New boxed expression editor - Support undo/redo in Boxed Expression Editor
kiegroup/kogito-editors-java pull request #120
Opened 2021-09-27 19:55 UTC by danielzhe

2021-09-29 00:34 UTC, danielzhe commented
Ready, @karreiro, @jomarko , @tiagobento

2021-09-30 08:08 UTC, jomarko commented
@danielzhe I found an issue, if user works with multiple nodes expressions in parallel. See more details in https://issues.redhat.com/browse/KOGITO-4195?focusedCommentId=19094068&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19094068.

2021-10-05 02:48 UTC, danielzhe commented
Thank you, @jomarko ! Looks like the issue you reported is present in main. I think this is very old issue, btw.
I also noticed that maybe you are testing the old boxed expression editor, because I realized that they are not available in VSCode yet because of [this PR](https://github.com/kiegroup/kogito-tooling/pull/631) that is not merged. Sorry about that. So I build it locally and I'm providing the Vsix for the reviews to test: https://drive.google.com/file/d/1RM-OjNv6WTDHjt-XMDefmXVXTUaD941Z/view?usp=sharing

2021-10-05 11:42 UTC, vpellegrino commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java
> -            final Definition definition = (Definition) element.getContent();
Can you please help me to understand how these methods are mapped with the new implementation?

2021-10-05 11:54 UTC, jomarko reviewed
@danielzhe thank you for the vsix, 

however I am not able to verify manually scenarios , where user work with more expressions in parallel. See my comment https://github.com/kiegroup/kogito-tooling/pull/631#pullrequestreview-771337733

2021-10-05 12:48 UTC, jomarko requested changes
I found out that decision table - add column operation can not be undone.

1. open a DMN file
2. add a decision node
3. open its expression editor
4. activate new expression editor
5. set expression as decision table
6. insert output column (I was able to reproduce with any kind of a column)
7. try to undo as 'Ctrl+Z' - **the added column will be still present**

2021-10-05 12:50 UTC, jomarko commented
@danielzhe @vpellegrino reading the comments here, now I got confused, should I use for testing of a #120 PR provided VSIX or a dmn-kogito-testing webapp?

2021-10-05 13:02 UTC, vpellegrino commented
> @danielzhe @vpellegrino reading the comments here, now I got confused, should I use for testing of a #120 PR provided VSIX or a dmn-kogito-testing webapp?

I think you should use the VSIX that @danielzhe has provided to you.
About the `dmn-webapp-kogito-testing`, my comment (https://github.com/kiegroup/kogito-editors-java/pull/120#pullrequestreview-771328922) was just to thank @danielzhe for enabling undo/redo feature also on that webapp, since previously it was not present.

2021-10-05 13:17 UTC, jomarko commented
@vpellegrino ok, then we are fine. I used VSIX.

2021-10-06 06:36 UTC, yesamer commented on kie-wb-common-dmn/kie-wb-common-dmn-api/src/main/java/org/kie/workbench/common/dmn/api/definition/model/DecisionRule.java
> +                return false;
@danielzhe These 2 if can be merged

2021-11-04 08:15 UTC, jomarko reviewed
One comment to code, I would like to recheck manually after #155 merge.

2021-11-04 08:15 UTC, jomarko commented on kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/util/UserActionCheckerTest.java
> +                                                                             "hit policy",
it seems we forget to use DATA_TYPE and HIT_POLICY on some places in this test class?

2021-12-02 20:45 UTC, closed without merging