KOGITO-5676: BPMN Editor - Containment not working when Node overlaps the Connector while splicing
kiegroup/kogito-editors-java pull request #95
Opened 2021-08-11 20:29 UTC by handreyrc

Hey @romartin, please could you review this PR?

**JIRA**: [KOGITO-5676](https://issues.redhat.com/browse/KOGITO-5676)

**VS Code**: [plugin](https://drive.google.com/file/d/1NaXYAgwd2ljYWF6ZTdAuQi0kj3X1QQZY/view?usp=sharing)

Thanks

2021-08-16 13:55 UTC, romartin approved these changes
Looks good to me, thanks @handreyrc !

2021-08-19 22:58 UTC, handreyrc commented
Hey @romartin @LuboTerifaj,
I fixed a small side-effect, added more unit tests, rebased and updated the plugin.  This PR is ready for review and testing again.

Thanks!

2021-08-20 09:10 UTC, LuboTerifaj commented
Hello @handreyrc , VSCode extension is missing in both google drive you linked here and the build in PR's checks. Can you please have a look at it? Thanks!

2021-08-20 09:22 UTC, LuboTerifaj reviewed
Hello @handreyrc , 

I couldn't have reproduce the issue on main branch. Could you please add the steps to reproduce to the jira? See also my [comment](https://issues.redhat.com/browse/KOGITO-5676?focusedCommentId=18854146&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-18854146) there.

Thank you!

2021-08-20 19:35 UTC, handreyrc commented
Hey @LuboTerifaj,
It's strange you could,t get the vscode plugin from my link, maybe some browser cache issue. 
Anyway here goes a new link for the plugin:

**VS Code**: [plugin](https://drive.google.com/file/d/1yGvvu7NSdkIwhpgRHqrcYDOdXO4VF7uV/view?usp=sharing) 

I already updated the issue with the steps to reproduce it as well, please ping me if you can't reproduce it yet.

The FDB is failing due to some unrelated issue, I'll keep an eye to get it green.

Thanks for checking it!

2021-08-23 09:35 UTC, karreiro approved these changes
Thank you, @handreyrc! Great stuff :-)

2021-08-23 20:10 UTC, handreyrc commented
Hey @LuboTerifaj we have all green here.
I tried to answer your questions in the JIRA the best I could I hope it helps.
I tested the lastest main and I could reproduce the issue. 
Please ping me if you can't reproduce it yet and we can do a quick call.

Thanks!

2021-08-25 14:38 UTC, LuboTerifaj requested changes
Hello @handreyrc , I have updated the steps to reproduce in jira.

I didn't find any issues. The fix works as expected.

However, I have one comment regarding code.

I have found related issue regarding the sequence flow colour inside containers (present also on main branch), but I have reported it in separate jira:

- [KOGITO-5778](https://issues.redhat.com/browse/KOGITO-5778) Sequence flow is red during Line splicing inside containers

Thank you!

2021-08-25 14:38 UTC, LuboTerifaj commented on lienzo-tests/src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresLineSpliceControlImplTest.java
> +    public void testExecuteSpliceWithContainmentWithDeviation() {
There are many common lines of code in `testExecuteSpliceWithContainmentWithoutDeviation` and `testExecuteSpliceWithContainmentWithDeviation` test methods. Would it make sense to you to refactor it a little bit? You could create a method for common code for example.

2021-08-30 12:01 UTC, LuboTerifaj approved these changes
Hello @handreyrc , The extension you have linked in the comment above works as expected. Thanks!

2021-09-01 21:49 UTC, romartin commented
Hey @handreyrc , Can I merge this? I see the FDB failing, is it something related to this PR or we can go ahead? Thx

2021-09-03 13:38 UTC, handreyrc commented
Hey @romartin,

This PR is rebased and finally has a green FDB. It is ready to merge!

Thanks!

2021-09-10 18:40 UTC, merged